"""Public API for agent-runtime-kit."""

from agent_runtime_kit._errors import (
    AgentRuntimeError,
    AgentRuntimeUnavailableError,
    OutputTypeError,
    RuntimeNotRegisteredError,
    UnsupportedTaskInputError,
)
from agent_runtime_kit._kit import KIND_ALIASES, AgentKit
from agent_runtime_kit._runtime import FakeAgentRuntime
from agent_runtime_kit._types import (
    AgentCapabilities,
    AgentResult,
    AgentRuntime,
    AgentRuntimeKind,
    AgentTask,
    ArtifactRef,
    AvailabilityReason,
    EventSink,
    FilesystemAccess,
    FinishReason,
    McpServerConfig,
    ParsedResult,
    PermissionMode,
    PermissionProfile,
    RuntimeAvailability,
    SessionResumeState,
    ToolCallAudit,
    Usage,
    runtime_kind_value,
)
from agent_runtime_kit.events import (
    output_delta_event,
    safe_emit,
    task_completed_event,
    task_failed_event,
    task_started_event,
    tool_completed_event,
    tool_requested_event,
    vendor_turn_event,
)
from agent_runtime_kit.registry import RuntimeRegistry, create_default_registry

__all__ = [
    "AgentCapabilities",
    "AgentKit",
    "AgentResult",
    "AgentRuntime",
    "AgentRuntimeError",
    "AgentRuntimeKind",
    "AgentRuntimeUnavailableError",
    "AgentTask",
    "ArtifactRef",
    "AvailabilityReason",
    "EventSink",
    "FakeAgentRuntime",
    "FilesystemAccess",
    "FinishReason",
    "KIND_ALIASES",
    "McpServerConfig",
    "OutputTypeError",
    "ParsedResult",
    "PermissionMode",
    "PermissionProfile",
    "RuntimeAvailability",
    "RuntimeNotRegisteredError",
    "RuntimeRegistry",
    "SessionResumeState",
    "ToolCallAudit",
    "UnsupportedTaskInputError",
    "Usage",
    "create_default_registry",
    "runtime_kind_value",
    "output_delta_event",
    "safe_emit",
    "task_completed_event",
    "task_failed_event",
    "task_started_event",
    "tool_completed_event",
    "tool_requested_event",
    "vendor_turn_event",
]
