"""Public API for agent-runtime-kit."""

from agent_runtime_kit._errors import (
    AgentRuntimeError,
    AgentRuntimeUnavailableError,
    AgentTaskTimeoutError,
    OutputSchemaError,
    OutputTypeError,
    RuntimeNotRegisteredError,
    UnsupportedTaskInputError,
)
from agent_runtime_kit._kit import KIND_ALIASES, AgentKit
from agent_runtime_kit._runtime import FakeAgentRuntime
from agent_runtime_kit._types import (
    AgentCapabilities,
    AgentResult,
    AgentRuntime,
    AgentRuntimeKind,
    AgentTask,
    ArtifactRef,
    AvailabilityReason,
    CancellationDisposition,
    CancellationReceipt,
    EventSink,
    FilesystemAccess,
    FinishReason,
    McpServerConfig,
    ParsedResult,
    PermissionMode,
    PermissionProfile,
    ReadinessStatus,
    RuntimeAvailability,
    RuntimeReadiness,
    RuntimeReadinessProvider,
    SessionResumeState,
    TaskSupportIssue,
    TaskSupportProvider,
    TaskSupportReport,
    ToolCallAudit,
    Usage,
    runtime_kind_value,
)
from agent_runtime_kit.compatibility import (
    COMPATIBILITY_MANIFEST,
    PackageVersion,
    RuntimeCompatibility,
    compatibility_for,
)
from agent_runtime_kit.events import (
    output_delta_event,
    safe_emit,
    task_completed_event,
    task_failed_event,
    task_started_event,
    tool_completed_event,
    tool_requested_event,
    vendor_turn_event,
)
from agent_runtime_kit.readiness import DEFAULT_READINESS_TIMEOUT, check_readiness
from agent_runtime_kit.registry import RuntimeRegistry, create_default_registry
from agent_runtime_kit.support import validate_task

__all__ = [
    "AgentCapabilities",
    "AgentKit",
    "AgentResult",
    "AgentRuntime",
    "AgentRuntimeError",
    "AgentRuntimeKind",
    "AgentRuntimeUnavailableError",
    "AgentTask",
    "AgentTaskTimeoutError",
    "ArtifactRef",
    "AvailabilityReason",
    "CancellationDisposition",
    "CancellationReceipt",
    "COMPATIBILITY_MANIFEST",
    "DEFAULT_READINESS_TIMEOUT",
    "EventSink",
    "FakeAgentRuntime",
    "FilesystemAccess",
    "FinishReason",
    "KIND_ALIASES",
    "McpServerConfig",
    "OutputSchemaError",
    "OutputTypeError",
    "PackageVersion",
    "ParsedResult",
    "PermissionMode",
    "PermissionProfile",
    "ReadinessStatus",
    "RuntimeAvailability",
    "RuntimeCompatibility",
    "RuntimeNotRegisteredError",
    "RuntimeReadiness",
    "RuntimeReadinessProvider",
    "RuntimeRegistry",
    "SessionResumeState",
    "TaskSupportIssue",
    "TaskSupportProvider",
    "TaskSupportReport",
    "ToolCallAudit",
    "UnsupportedTaskInputError",
    "Usage",
    "create_default_registry",
    "compatibility_for",
    "check_readiness",
    "runtime_kind_value",
    "output_delta_event",
    "safe_emit",
    "task_completed_event",
    "task_failed_event",
    "task_started_event",
    "tool_completed_event",
    "tool_requested_event",
    "vendor_turn_event",
    "validate_task",
]
